# Generated by Django 5.0.3 on 2024-03-15 22:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_User_Settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='Custom_User_Settings',
        ),
    ]
