# Generated by Django 5.0.3 on 2024-03-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_User_Settings', '0002_rename_usersettings_custom_user_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user_settings',
            old_name='darkMode',
            new_name='dark_mode',
        ),
    ]
