# Generated by Django 5.0.6 on 2024-07-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_User_Settings', '0003_rename_darkmode_custom_user_settings_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user_settings',
            name='retain_last_used_options',
            field=models.BooleanField(default=False),
        ),
    ]
