# Generated by Django 5.0.6 on 2024-07-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_User_Settings', '0004_custom_user_settings_retain_last_used_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user_settings',
            name='theme',
            field=models.CharField(default='galactic_blood', max_length=20),
        ),
    ]
