# Generated by Django 5.1 on 2024-08-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_User_Settings', '0005_custom_user_settings_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user_settings',
            name='language',
        ),
    ]
