# Generated by Django 4.2.9 on 2024-04-05 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolpageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.BooleanField(default=False)),
                ('formal', models.BooleanField(default=False)),
                ('academic', models.BooleanField(default=False)),
                ('creative', models.BooleanField(default=False)),
                ('study_notes', models.BooleanField(default=False)),
                ('meeting_notes', models.BooleanField(default=False)),
                ('email_and_memo', models.BooleanField(default=False)),
                ('outline', models.BooleanField(default=False)),
                ('story_telling', models.BooleanField(default=False)),
                ('research_paper', models.BooleanField(default=False)),
                ('report', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
