# Generated by Django 5.0.6 on 2024-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpagetemplate',
            name='bionic_reading',
            field=models.BooleanField(default=False),
        ),
    ]
