# Generated by Django 5.0.3 on 2024-03-15 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedUserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_template', models.CharField(max_length=200, unique=True)),
                ('summary', models.BooleanField()),
                ('formal', models.BooleanField()),
                ('academic', models.BooleanField()),
                ('creative', models.BooleanField()),
                ('study_notes', models.BooleanField()),
                ('meeting_notes', models.BooleanField()),
                ('email_and_memo', models.BooleanField()),
                ('outline', models.BooleanField()),
                ('story_telling', models.BooleanField()),
                ('research_paper', models.BooleanField()),
                ('report', models.BooleanField()),
                ('resume', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
