# Generated by Django 4.2.9 on 2024-04-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SavedUserTemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedusertemplate',
            name='academic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='creative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='email_and_memo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='formal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='meeting_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='outline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='research_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='story_telling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='study_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedusertemplate',
            name='summary',
            field=models.BooleanField(default=False),
        ),
    ]
