# Generated by Django 5.0.6 on 2024-07-20 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_last_prompt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_file_upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
